FROM --platform=linux/amd64 node:16-slim

WORKDIR /app

# Install required packages
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    python3-minimal \
    make \
    g++ \
    && rm -rf /var/lib/apt/lists/*

# Install dependencies and build
CMD ["sh", "-c", "npm install && npm run build"]